### ISSUE TITLE
React-native project using mobservable-react

### ISSUE THREAD

**Issue by jjchula** [mweststrate/mobservable-react#16]
Thank you for the Boilerplate projects. But they are for JSX or the web.
Would you provide a React-native project using mobservable-react or point me to a demo please?

**Comment by mweststrate** [comment]
I didn't built a react-native project myself using mobservable, but I know there are some people on the gitter / reactiflux channel who did so probably you can ask around in these channels.

Besides that, integration mobservable with react native is really easy; just use the `@observer` decorator on your react native components instead of on JSX based components, that should be all. If you don't use ES6 syntax, just pass your components through `observer`: `var myNativeComponent = mobservableReact.observer(React.createClass({ .. }));`

**Comment by jjchula** [comment]
I've tried but it didn't work.

"import observer from mobservable-react/native" and "export default observer(myComponent)" didn't make the trick. It ends up in different errors for different versions of react native. So I might miss something.

A working demo would greatly help.

**Comment by mweststrate** [comment]
Note that it should be ..import {observer} from
"mobservable-react/native".. If that doesn't help I'm gonna try to find
somebody who uses it with native for you :)

**Comment by jjchula** [comment]
Right! It's working now. Many thanks.

I was too lazy so I took the code from README.md. Noted the broken link.

## Installation
...
import observer from 'mobservable-react';
// - or -
import observer from 'mobservable-react/native';

This package provides the bindings for Mobservable and React. See the __broken link__ for how to get started.

**Comment by mweststrate** [comment]
Ouch, that's really embarrassing. Fixed it. Thanks for reporting!
