### ISSUE TITLE
(4,36): error TS2503: Cannot find namespace 'React'.

### ISSUE THREAD

**Issue by kenotron** [mweststrate/mobservable-react#5]
When using Typescript 1.6.2 with mobservable-react, I simply do this:

import {observer} from 'mobservable-react';

However, index.d.ts doesn't have a declaration of React available. So it would give this error:

(4,36): error TS2503: Cannot find namespace 'React'.

Perhaps you have a way to use TS with mobservable-react that isn't apparent?

**Comment by mweststrate** [comment]
Hi,

You have to manually include the typings of the React package in your project, as available in the [public typings repo](https://github.com/borisyankov/DefinitelyTyped/tree/master/react) or through the tsd tool using `tsd install react --save`. If you refer it from one of your source files you should be OK.

This is a result of the limitation in TypeScript that it is not possible to ship (ambient) declarations of a dependent package in a package. I'll add it to the readme, thanks for pointing out.

**Comment by kenotron** [comment]
Now, I do have an index.d.ts that has a /// <reference> block referencing react.d.ts. This is why I'm confused why this is happening.

Do you have an example set up where this works?

**Comment by mweststrate** [comment]
Yes, you cannot avoid that, it is what typescript emits after compiling. We
usually strip those out using some sed script / patch / whatever. Which
then moves the responsibility of providing react.d.ts to the consumers of
the lib you might be building. It's sad, but it is the best typescript has
to offer atm for packages that don't ship with their own typings (as is the
case we many large libs like react, lodash, node, etc). We spend literally
weeks over the past half year I think in finding the best approach. At
least it has become a little bit better since typescript 1.6.2, before that
commonjs packages where not able to ship typings at all.

**Comment by mweststrate** [comment]
If you don't care that much about the React typings, I think it might be possible to declare a minimal subset so that the compiler accepts the `mobservable-react` typings, something like:

```typescript
declare module "React" {
    export class ComponentClass<T> { }
    export class ClassicComponentClass<T> { }
    export class ReactElement<T> { }
}
```

Another workaround is to import mobservable-react untyped, like: `var mobservableReact = require('mobservable-react')`.

**Comment by kenotron** [comment]
re: my comment - I actually did do what you said here: 

"You have to manually include the typings of the React package in your project, as available in the public typings repo or through the tsd tool using tsd install react --save. If you refer it from one of your source files you should be OK"

and I'm still stuck with mobservable-react assuming that I have React defined somewhere. I currently use the react.d.ts to 

````
/* one of my source files */
/// <reference path="../typings/tsd.d.ts" />
import * as React from 'react';
import {observer} from 'mobservable-react';
````

I am guessing you have a solution in your own projects for this - what route did you choose to solve this problem?

**Comment by kenotron** [comment]
The only way I can get around it is ignore types with:

let {observer} = require("mobservable-react");

This is sad though, because the whole point of including a index.d.ts is to be able to use it in a project.

**Comment by mweststrate** [comment]
Our setup is currently like this:

```javascript
/// <reference path='../typings.d.ts'/>
var React = require('react/addons');

import {observer} from "mobservable-react";
```

and inside typings.d.ts:

```/// <reference path='../../typings/react/react-global.d.ts'/>```

If that still doesn't work, I'll setup a a reference Typescript / TSX / mobservable project

**Comment by mweststrate** [comment]
I reproduced the issue on a fresh project that doesn't use the `react-global` typings. I've improved the typings accordingly in version 1.0.1 and created a ready-to-use repo for typescript here: 

https://github.com/mweststrate/mobservable-react-typescript (based on @bvanreeven minimal typescript repo).

I hope that solves the issue!

**Comment by kenotron** [comment]
Fixed!!! Thank you @mweststrate :) That was quick work!
